version: '3.7'
services:
  mongo:
    image: bitnami/mongodb:4.2
    volumes:
      - db:/data/db
    environment:
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
  mongo-express:
    image: mongo-express:0.54
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT}
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_AUTH_DATABASE=${MONGODB_DATABASE}
    ports:
      - 8081:8081
volumes:
  db:
