version: '3.7'

services:
  mongo:
    image: bitnami/mongodb:4.2
    volumes:
      - faceit_blacklist_data:/data/db
    env_file:
      - .env.development
  mongo-express:
    image: mongo-express:0.54
    env_file:
      - .env.development
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT}
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_AUTH_DATABASE=${MONGODB_DATABASE}
    ports:
      - 8081:8081
volumes:
  faceit_blacklist_data:
